name: Tests with Allure Report

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pytest allure-pytest

    - name: Run tests with Allure
      run: pytest test_hello.py --alluredir=allure-results -v
      continue-on-error: true

    - name: Checkout GitHub Pages
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Generate Allure Report
      uses: andgineer/allure-report@v3.6
      id: allure-report
      if: always()
      with:
        allure-results: allure-results
        website: gh-pages-dir
        reports-site-path: reports

    - name: Publish Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: gh-pages-dir
        destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}